# Generated by Django 2.2.5 on 2020-06-28 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DagboekPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('mijlpaal', models.CharField(blank=True, max_length=100, null=True)),
                ('sprong', models.BooleanField(default=False, verbose_name='Sprong')),
                ('titel', models.CharField(blank=True, max_length=100, null=True)),
                ('beschrijving', models.CharField(blank=True, max_length=7000, null=True)),
                ('gewicht', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True)),
                ('lengte', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True)),
                ('uurvanOpstaan', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Wakker geworden om:')),
                ('uurvanSlapen', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Gaan slapen om:')),
                ('favpost', models.BooleanField(default=False, verbose_name='Favoriete post')),
                ('nachtflesjes', models.IntegerField(blank=True, default=0, null=True, verbose_name='Aantal nachtflesjes:')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='mykids/')),
                ('fav', models.BooleanField(default=False, verbose_name='Favoriet')),
                ('type', models.CharField(choices=[('Img', 'Image'), ('Vid', 'Video')], max_length=20, null=True)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('dagboekpost', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mykids.DagboekPost')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
