# Generated by Django 2.2.5 on 2020-07-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='alltimefav',
            field=models.BooleanField(default=False, verbose_name='All time fav'),
        ),
    ]
