# Generated by Django 2.2.5 on 2020-08-07 15:13

from django.db import migrations, models
import mykids.models


class Migration(migrations.Migration):

    dependencies = [
        ('mykids', '0004_media_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(null=True, upload_to=mykids.models.generate_filename),
        ),
    ]
