# Generated by Django 2.2.5 on 2020-08-07 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mykids', '0006_auto_20200807_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='dagboekpost',
            name='naam',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
