# Generated by Django 2.2.5 on 2020-08-22 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mykids.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mykids', '0010_auto_20200818_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.FileField(null=True, upload_to=mykids.models.generate_filename)),
                ('fav', models.BooleanField(default=False, verbose_name='Favoriet')),
                ('alltimefav', models.BooleanField(default=False, verbose_name='All time fav')),
                ('desc', models.CharField(blank=True, max_length=7000, null=True)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('dagboekpost', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mykids.DagboekPost')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('dagboekpost',),
            },
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('dagboekpost',)},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='naam',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='type',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
