# Generated by Django 3.0.6 on 2021-04-24 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mykids', '0011_auto_20200822_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mijlpaal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='dagboekpost',
            options={'ordering': ('-datum',)},
        ),
        migrations.AlterField(
            model_name='dagboekpost',
            name='mijlpaal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mykids.Mijlpaal'),
        ),
    ]
