# Generated by Django 3.0.6 on 2021-04-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykids', '0012_auto_20210424_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mijlpaal',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='dagboekpost',
            name='naam',
            field=models.CharField(max_length=10),
        ),
    ]
