# Generated by Django 3.0.6 on 2021-09-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykids', '0016_auto_20210913_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dagboekpost',
            old_name='titel',
            new_name='titel_lotte',
        ),
        migrations.AddField(
            model_name='dagboekpost',
            name='titel_merlijn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
