# Generated by Django 3.0.6 on 2021-09-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mykids', '0020_auto_20210920_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mykids.Rating'),
        ),
        migrations.AlterField(
            model_name='video',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mykids.Rating'),
        ),
    ]
