# Generated by Django 3.0.6 on 2021-09-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykids', '0021_auto_20210920_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imglotte',
            field=models.BooleanField(default=False, verbose_name='Lotte'),
        ),
        migrations.AddField(
            model_name='image',
            name='imgmama',
            field=models.BooleanField(default=False, verbose_name='Mama'),
        ),
        migrations.AddField(
            model_name='image',
            name='imgmerlijn',
            field=models.BooleanField(default=False, verbose_name='Merlijn'),
        ),
        migrations.AddField(
            model_name='image',
            name='imgpapa',
            field=models.BooleanField(default=False, verbose_name='Papa'),
        ),
        migrations.AddField(
            model_name='video',
            name='vidlotte',
            field=models.BooleanField(default=False, verbose_name='Lotte'),
        ),
        migrations.AddField(
            model_name='video',
            name='vidmama',
            field=models.BooleanField(default=False, verbose_name='Mama'),
        ),
        migrations.AddField(
            model_name='video',
            name='vidmerlijn',
            field=models.BooleanField(default=False, verbose_name='Merlijn'),
        ),
        migrations.AddField(
            model_name='video',
            name='vidpapa',
            field=models.BooleanField(default=False, verbose_name='Papa'),
        ),
    ]
