# Generated by Django 3.0.6 on 2021-09-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mykids', '0022_auto_20210921_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='image',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tag',
        ),
    ]
