# Generated by Django 2.2.5 on 2020-08-07 13:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Specialism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('specialism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhealth.Specialism')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('upsurge', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhealth.Doctor')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhealth.Location')),
                ('specialism', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhealth.Specialism')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
