# Generated by Django 2.2.5 on 2020-08-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='specialism',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='consultation',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
