# Generated by Django 2.2.5 on 2020-09-30 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0002_auto_20200807_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('aantal_ochtend', models.IntegerField(blank=True, default=0, null=True, verbose_name='Aantal nachtflesjes:')),
                ('aantal_avond', models.IntegerField(blank=True, default=0, null=True, verbose_name='Aantal nachtflesjes:')),
                ('pijn', models.BooleanField(default=False, verbose_name='Pijn')),
            ],
        ),
    ]
