# Generated by Django 2.2.5 on 2020-10-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0003_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='aantal_avond',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Avond:'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='aantal_ochtend',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ochtend:'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='pijn',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Avond:'),
        ),
    ]
