# Generated by Django 2.2.5 on 2020-10-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0004_auto_20201001_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='medicatie',
            field=models.CharField(default='Salozyprine', max_length=1000, null=True),
        ),
    ]
