# Generated by Django 2.2.5 on 2020-10-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0006_medication_opmerking'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='linkerhand',
            field=models.BooleanField(default=False, verbose_name='Linker hand'),
        ),
        migrations.AddField(
            model_name='medication',
            name='linkervoet',
            field=models.BooleanField(default=False, verbose_name='Linker voet'),
        ),
        migrations.AddField(
            model_name='medication',
            name='rechterhand',
            field=models.BooleanField(default=False, verbose_name='Rechter hand'),
        ),
        migrations.AddField(
            model_name='medication',
            name='rechtervoet',
            field=models.BooleanField(default=False, verbose_name='Rechter voet'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='pijn',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pijn-niveau (0,1,2):'),
        ),
    ]
