# Generated by Django 2.2.5 on 2020-11-07 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0007_auto_20201024_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='medication',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
