# Generated by Django 2.2.5 on 2020-12-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0008_auto_20201107_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='rug',
            field=models.BooleanField(default=False, verbose_name='Rug'),
        ),
    ]
