# Generated by Django 3.0.6 on 2021-04-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0009_medication_rug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='pijn',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pijn-niveau (0,1,2,3):'),
        ),
    ]
