# Generated by Django 2.2.5 on 2020-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('-name',)},
        ),
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
