# Generated by Django 2.2.5 on 2020-08-02 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0003_auto_20200731_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(null=True, upload_to='mykids/')),
                ('transaction', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myfinances.Transaction')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
