# Generated by Django 2.2.5 on 2020-08-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0004_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.FileField(null=True, upload_to='myfinances/'),
        ),
    ]
